### ISSUE TITLE
请求搜索问题

### ISSUE THREAD

**Issue by NuonuoLabs** [jiyouliang/FMap#4]
我想请教下像高德搜索附近怎么实现的？例如我搜老乡鸡怎么出现离我比较近的再最上面？
我看了你的demo，用InputtipsQuery搜索而且只能展示10条数据，数据也是高德返回的没有做什么处理。请求下思路

**Comment by X-ljy** [comment]
发错对象了吧。。。

发送自 Windows 10 版邮件应用

发件人: 1825492258
发送时间: 2019年12月4日 18:11
收件人: jiyouliang/FMap
抄送: Subscribed
主题: [jiyouliang/FMap] 请求搜索问题 (#4)

我想请教下像高德搜索附近怎么实现的？例如我搜老乡鸡怎么出现离我比较近的再最上面？
我看了你的demo，用InputtipsQuery搜索而且只能展示10条数据，数据也是高德返回的没有做什么处理。请求下思路

**Comment by locker777** [comment]
你为什么老发给我





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"青夕"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月5日(星期四) 晚上8:31
收件人:&nbsp;"jiyouliang/FMap"<FMap@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [jiyouliang/FMap] 请求搜索问题 (#4)



发错对象了吧。。。 
 
 发送自 Windows 10 版邮件应用 
 
 发件人: 1825492258 
 发送时间: 2019年12月4日 18:11 
 收件人: jiyouliang/FMap 
 抄送: Subscribed 
 主题: [jiyouliang/FMap] 请求搜索问题 (#4) 
 
 我想请教下像高德搜索附近怎么实现的？例如我搜老乡鸡怎么出现离我比较近的再最上面？ 
 我看了你的demo，用InputtipsQuery搜索而且只能展示10条数据，数据也是高德返回的没有做什么处理。请求下思路

**Comment by X-ljy** [comment]
？？？ 谁发给你了

发送自 Windows 10 版邮件应用

发件人: locker777
发送时间: 2019年12月5日 20:32
收件人: jiyouliang/FMap
抄送: 青夕; Comment
主题: Re: [jiyouliang/FMap] 请求搜索问题 (#4)

你为什么老发给我 





------------------&nbsp;原始邮件&nbsp;------------------ 
发件人:&nbsp;"青夕"<notifications@github.com&gt;; 
发送时间:&nbsp;2019年12月5日(星期四) 晚上8:31 
收件人:&nbsp;"jiyouliang/FMap"<FMap@noreply.github.com&gt;; 
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;; 
主题:&nbsp;Re: [jiyouliang/FMap] 请求搜索问题 (#4) 



发错对象了吧。。。 

发送自 Windows 10 版邮件应用 

发件人: 1825492258 
发送时间: 2019年12月4日 18:11 
收件人: jiyouliang/FMap 
抄送: Subscribed 
主题: [jiyouliang/FMap] 请求搜索问题 (#4) 

我想请教下像高德搜索附近怎么实现的？例如我搜老乡鸡怎么出现离我比较近的再最上面？ 
我看了你的demo，用InputtipsQuery搜索而且只能展示10条数据，数据也是高德返回的没有做什么处理。请求下思路
